CREATE TABLE book
(BOOK_ID int NOT NULL PRIMARY KEY,
ISBN char(13) NOT NULL,
TITLE varchar(50) NOT NULL,
AUTHOR varchar(50) NULL,
GENRE varchar(20) NULL,
AVAILABLE bit NOT NULL,
COST smallmoney NULL,
NUMBER_OF_COPIES TINYINT NOT NULL,
PUBLISHER_NAME varchar(50) NOT NULL,
PUBLISH_DATE date NOT NULL,
CREATION_DATE timestamp NOT NULL,
MODIFICATION_DATE timestamp NOT NULL);

CREATE TABLE CLIENT
(CLIENT_ID int NOT NULL PRIMARY KEY,
FIRST_NAME varchar(50) NOT NULL,
LAST_NAME varchar(50) NOT NULL,
ACCOUNT_BALANCE smallmoney NOT NULL,
CREATION_DATE timestamp NOT NULL,
MODIFICATION_DATE timestamp NOT NULL);