drop table book;
drop table user;
drop table book_checkout;

CREATE TABLE book
(BOOK_ID varchar(40) NOT NULL PRIMARY KEY,
ISBN varchar(13) NOT NULL,
TITLE varchar(50) NOT NULL,
AUTHOR varchar(50) NULL,
GENRE varchar(20) NULL,
AVAILABLE bit NOT NULL,
COST Double NULL,
PUBLISHER_NAME varchar(50) NOT NULL,
PUBLISH_DATE date NOT NULL,
CREATION_DATE timestamp NOT NULL,
MODIFICATION_DATE timestamp NOT NULL);

CREATE TABLE USER
(USER_ID varchar(40) NOT NULL PRIMARY KEY,
FIRST_NAME varchar(50) NOT NULL,
LAST_NAME varchar(50) NOT NULL,
ACCOUNT_BALANCE Double NOT NULL,
CREATION_DATE timestamp NOT NULL,
MODIFICATION_DATE timestamp NOT NULL);

CREATE TABLE book_checkout
(BOOK_CHECKOUT_ID varchar(40) NOT NULL PRIMARY KEY,
BOOK_ID int NOT NULL,
USER_ID int NOT NULL,
RENEWABLE bit NOT NULL,
DUE_DATE timestamp NOT NULL,
CREATION_DATE timestamp NOT NULL,
MODIFICATION_DATE timestamp NOT NULL);